{ self, inputs, config, lib, pkgs,
  host, repo, network, user,
  ...
}:
{
  # --- Stylix ---
  # Sets colors, fonts, & styles for multiple programs based on wallpaper.
  #
  # https://danth.github.io/stylix/options/hm.html
  #
  # To-do:
  # - [ ] TODO: Create fork of stylix
  stylix = rec {
    autoEnable = true;
    #base16Scheme = {};
    fonts = {
      emoji     = { name = "Noto Color Emoji"; package = pkgs.noto-fonts-emoji; };
      monospace = { name = "Maple Mono";       package = pkgs.maple-mono-NF;    };
      serif     = { name = "DejaVu Serif";     package = pkgs.dejavu-fonts;     };
      sansSerif = { name = "Cantarell";        package = pkgs.cantarell-fonts;  };
      #sansSerif = { name = "DejaVu Sans";      package = pkgs.dejavu-fonts;     };

      sizes = {
        applications = lib.mkDefault 11;
        desktop      = lib.mkDefault 10;
        popups       = lib.mkDefault 10;
        terminal     = lib.mkDefault 10;
      };
    };

    # --- Wallpaper ---
    #image = "${config.xdg.dataHome}/wallpapers/";

    # Override applied to `stylix.base16Scheme` when generating `lib.stylix.colors`
    #  Accepts anything that a scheme generated by base16nix can take as an argument to override
    override = lib.mkDefault {};

    # Force a light or dark theme
    polarity = lib.mkDefault "either";

    # Target programs to style
    #  List: alacritty, avizo, bemenu, bspwm, dunst, emacs, feh, fish, foot,
    #        gedit, gnome, gtk,
    #        helix, i3, k9s, kitty, mako, qutebrowser, rofi,
    #        sway, swaylock,
    #        sxiv, vim, vscode, waybar, xresources, zathura,
    targets = {
      bat.enable = lib.mkDefault true;
      bemenu = {
        enable    = lib.mkDefault true;
        alternate = lib.mkDefault false;
        fontSize  = lib.mkDefault fonts.sizes.applications;
      };
      gedit.enable = lib.mkDefault true;
      gnome.enable = true;
      gtk = {
        enable = true;
        # Extra code added to both `$XDG_CONFIG_HOME/gtk-{3,4}.0/gtk.css`
        #extraCss = ''
        #'';
      };
      kitty    = { enable = lib.mkDefault true; variant256Colors = lib.mkDefault false; };
      swaylock = { enable = lib.mkDefault true;         useImage = lib.mkDefault true;  };
      waybar = {
        enable = lib.mkDefault true;
        enableCenterBackColors = lib.mkDefault false;
        enableLeftBackColors   = lib.mkDefault false;
        enableRightBackColors  = lib.mkDefault false;
      };
      xresources.enable = true;
    };
  };
}
