# --- Hardware ---------------------------------------------

# --- Proprietary Drivers ---
# TODO: DisplayLink/evdi
# TODO: DisplayLink binary blobs
# https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/os-specific/linux/displaylink/default.nix#L71
#[displaylink]
#fetch.tarball: ""


# --- GNOME ------------------------------------------------
# --- Shell ---
# TODO: gnome.gnome-shell-latest
# TODO: gnome.gnome-shell-performance-patch

[gnome.gnome-shell-mobile]
# TODO: Create package
src.branch = "mobile-shell"
src.git = "https://gitlab.gnome.org/verdre/gnome-shell"
fetch.git = "https://gitlab.gnome.org/verdre/gnome-shell"

[gnome.gnome-shell-mobile-devel]
# TODO: Create package
src.branch = "mobile-shell-devel"
src.git = "https://gitlab.gnome.org/verdre/gnome-shell"
fetch.git = "https://gitlab.gnome.org/verdre/gnome-shell"

[gnome.mutter-mobile]
# TODO: Create package
src.branch = "mobile-shell"
src.git = "https://gitlab.gnome.org/verdre/mutter"
fetch.git = "https://gitlab.gnome.org/verdre/mutter"

[gnome.mutter-mobile-devel]
# TODO: Create package
src.branch = "mobile-shell-devel"
src.git = "https://gitlab.gnome.org/verdre/mutter"

# --- GNOME Online Accounts ---
# TODO: gnome.goaPlugins.ews
# TODO: gnome.goaPlugins.protonMail  # https://github.com/emersion/hydroxide

# --- GNOME Shell Extensions ---
# TODO: gnomeExtensions.forge-latest
# TODO: gnomeExtensions.ddterm-latest

[gnomeExtensions.latest.valent]
#[gnome-shell-extension-valent]
# TODO: Create package
fetch.github = "andyholmes/gnome-shell-extension-valent"
src.git = "https://github.com/andyholmes/gnome-shell-extension-valent"



# --- Applications -----------------------------------------

# --- AppImages ---
# --- Electron ----

# --- GTK ---------

[capsule]
# TODO: Create package
src.branch = "main"
src.git = "https://gitlab.gnome.org/verdre/Capsule"
fetch.git = "https://gitlab.gnome.org/verdre/Capsule"

[chatty]
# TODO: Fetch source from main, apply patch from merge request
#src.git = "https://source.puri.sm/Librem5/chatty"
#src.branch = "master"
src.git = "https://source.puri.sm/Librem5/chatty/-/merge_requests/1202.patch"
fetch.git = "https://source.puri.sm/Librem5/chatty"
git.fetchSubmodules = true

[latest.foliate]
fetch.github = "johnfactotum/foliate"
src.branch = "gtk4"
src.git = "https://github.com/johnfactotum/foliate"
git.fetchSubmodules = true

[latest.fractal]
fetch.git = "https://gitlab.gnome.org/GNOME/fractal"
src.git = "https://gitlab.gnome.org/GNOME/fractal"
src.branch = "main"
git.fetchSubmodules = true
cargo_locks = [ "Cargo.lock" ]

[hackgregator]
# TODO: Create package
fetch.git = "https://gitlab.com/gunibert/hackgregator"
src.git = "https://gitlab.com/gunibert/hackgregator"

[latest.valent]
fetch.github = "andyholmes/valent"
src.git = "https://github.com/andyholmes/valent"

# TODO: Background Remover
# TODO: Bavarder
# TODO: Flatseal
# TODO: GTKCord
# TODO: Login Manager
# TODO: Monophony
# TODO: Paper
# TODO: Ringman            # https://github.com/vacuumbeef/ringman
# TODO: Spedread
# TODO: Sticky Notes
# TODO: Upscaler
# TODO: Video Trimmer

# --- QT ------------
# TODO: Upscayl

# --- Misc Apps -----
# TODO: Arkenfox
# TODO: UngoogledChromium

# --- App Plugins ---
# TODO: GIMP GEGL Plugins
# TODO: GIMP Plugins
# TODO: Nautilus Extensions

# --- Themes -----------------------------------------------
# TODO: plymouthThemes.ad199x

# --- OS Images ---
# TODO: osImages.windows10
# TODO: osImages.windows11

# --- Shell ------------------------------------------------
# --- Tmux Plugins ---
# --- ZSH Plugins ----

# --- Editors ----------------------------------------------
# --- Neovim Extensions ---
# --- Vim Extensions ------
# --- Vim Themes ----------
# --- VSCode Extensions ---
# --- VSCode Themes -------

# --- Web Browsers -----------------------------------------
# --- Chrome Extensions ---
# --- Chrome Themes -------

# --- Firefox Themes ------

[firefox-gnome-theme]
fetch.github = "rafaelmardojai/firefox-gnome-theme"
src.git = "https://github.com/rafaelmardojai/firefox-gnome-theme"

[firefox-mobile-config]
fetch.git = "https://gitlab.com/postmarketOS/mobile-config-firefox"
src.git = "https://gitlab.com/postmarketOS/mobile-config-firefox"
src.branch = "main"


# --- Web Extensions ------
# --- userScripts ---------
# --- userStyles ----------


# --- Servers ----------------------------------------------
# TODO: Apache Guacamole
# TODO: AppDaemon
# TODO: Authentik
# TODO: Bazaar
# TODO: Bodgeit
# TODO: Booksonic
# TODO: ChartMuseum
# TODO: CloudBeaver
# TODO: CyberChef
# TODO: Draw.io
# TODO: echoserver
# TODO: Godbox
# TODO: Golinks
# TODO: Habitica
# TODO: Heimdall
# TODO: Homer
# TODO: Hoppscotch
# TODO: Huginn
# TODO: IPFS Web Gateway
# TODO: Immich
# TODO: KomposeUI
# TODO: LazyLibrarian
# TODO: LibrePhotos
# TODO: LibreSpeed
# TODO: LittleLink
# TODO: Lychee
# TODO: Mealie
# TODO: NodeRed
# TODO: Olivetin
# TODO: OpenEMR
# TODO: OmniDB
# TODO: Organizr
# TODO: phpLDAPadmin
# TODO: Pixapop
# TODO: pretend-your-xyzzy
# TODO: PyTorch
# TODO: Rainloop
# TODO: RoomAssistant
# TODO: Sharry
# TODO: Stash
# TODO: Statping
# TODO: Tdarr
# TODO: Traccar
# TODO: Vaultwarden Web
# TODO: Vouch Proxy
# TODO: Wallabag
# TODO: whoami
# TODO: wg-gen-web
# TODO: wger
# TODO: Whoogle
# TODO: YouTubeDL-Material
# TODO: YouTube Piped


# --- ML Models --------------------------------------------


# --- Android ----------------------------------------------

# --- Apps ---

# TODO: Aliucord Installer
# TODO: Aliucord
# TODO: Aurora Store
# TODO: Element
# TODO: FluffyChat
# TODO: FluffyChat Nightly
# TODO: Kvaesito Launcher
# TODO: Kvaesito Icons
# TODO: LawnchairLauncher/Lawnchair
# TODO: LawnchairLauncher/Lawnicons
# TODO: LawnchairLauncher/Lawnfeed
# TODO: Magisk Manager
# TODO: Magisk Plugins
# TODO: NeoApplications/NeoStore
# TODO: NeoApplications/NeoFeed
# TODO: NeoApplications/NeoLauncher
# TODO: NextPush
# TODO: Nextcloud Notes
# TODO: NS-USBLoader
# TODO: Obtainium
# TODO: Read You
# TODO: Rekado
# TODO: Revanced Manager
# TODO: Simple Calculator
# TODO: Simple Contacts
# TODO: Simple Dialer
# TODO: Simple Draw
# TODO: Simple Gallery
# TODO: Simple SMS Messenger
# TODO: sms-matrix
# TODO: Termux API
# TODO: Termux Boot
# TODO: Termux GUI
# TODO: Termux Nix
# TODO: Termux Styles
# TODO: Termux Tasker
# TODO: Termux Widgets
# TODO: UnifiedPush

# --- OS Sources --
# TODO: osSources.android.AOSP
# TODO: osSources.android.CalyxOS
# TODO: osSources.android.DivestOS
# TODO: osSources.android.GrapheneOS
# TODO: osSources.android.LineageOS

# --- Nintendo Modding -------------------------------------
# --- Emulation ---------
# TODO: Brawl Project+
# TODO: Melee Slippi Launcher
# TODO: Melee Universal Controller Fix
# TODO: Melee UnclePunch Training Pack

# --- Libraries ---------
# TODO: nintendo-switch.libs.devkitpro

# --- Skyline Plugins ---
# TODO: nintendo-switch.smash.skylinePlugins.arcropolis
# TODO: nintendo-switch.smash.skylinePlugins.auto-refresh
# TODO: nintendo-switch.smash.skylinePlugins.discord-presence
# TODO: nintendo-switch.smash.skylinePlugins.hdr
# TODO: nintendo-switch.smash.skylinePlugins.hitbox-visualizer
# TODO: nintendo-switch.smash.skylinePlugins.input-visualizer
# TODO: nintendo-switch.smash.skylinePlugins.oneslot-victory-theme
# TODO: nintendo-switch.smash.skylinePlugins.oneslot-effects
# TODO: nintendo-switch.smash.skylinePlugins.smash-minecraft-skins
# TODO: nintendo-switch.smash.skylinePlugins.smush-info
# TODO: nintendo-switch.smash.skylinePlugins.ultimate-training-modpack

# --- System ------------
# TODO: atmosphere-nx/atmosphere
# TODO: CTCaer/hekate
# TODO: exelix11/sysDVR
# TODO: exelix11/dvr-patches
# TODO: nintendo-switch.sysmodules.sys-ftpd

# --- SD Card Assets ----
# TODO: nintendo-switch.smash.assets.hdr

# --- Payloads ---
# TODO: nintendo-switch.payloads.fusee
# TODO: nintendo-switch.payloads.IncognitoRCM
# TODO: nintendo-switch.payloads.LockpickRCM

# --- System Firmware ---
# TODO: nintendo-switch.system-firmware.latest
