#
# https://docs.k3s.io/advanced#nvidia-container-runtime-support
#
# 1. Install nvidia-container package repository.
#   - Instructions: https://nvidia.github.io/libnvidia-container/
# 2. Install nvidia-container runtime packages
# 3. Install k3s or restart if installed
# 4. Confirm nvidia container runtime has been found by k3s
# 5. Install this manifest in Kubernetes cluster
# 6. https://github.com/NVIDIA/k8s-device-plugin/
# 7. https://github.com/NVIDIA/gpu-feature-discovery/
# Optional: https://rootlesscontaine.rs/
#
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia
---
apiVersion: v1
kind: Pod
metadata:
  name: nbody-gpu-benchmark
  namespace: default
spec:
  restartPolicy: OnFailure
  runtimeClassName: nvidia
  containers:
    - name: cuda-container
      image: nvcr.io/nvidia/k8s/cuda-sample:nbody
      args: ["nbody", "-gpu", "-benchmark"]
      resources:
        limits:
          nvidia.com/gpu: 1
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all
