test-shared-secret: ENC[AES256_GCM,data:BCqw5HvY,iv:rN7vOzYKXX/RD7v/l9BrdXuyOTaZBdPiIcu6fUpq2NU=,tag:WpSv2ld8fKay5x5FPR7OzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ussjg6kmjawm6zhfkspnujndx48a8yzlg6sew0gzyu74gpr8amq9g9udd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbTFnUEtDdjBkYXNtYkFF
            c0d6THdWYzV1UURpS2wxYi9yWHdJYURCMDNZCllsVHFveFUxOUZaMVNEWEJGUU0y
            dVR2TjJ6RGppMGVhbXBuUWlaQXNMTmcKLS0tIElJdWFMSHRmbGk5M3V0THoxREh4
            dEpTZmtMNU1ZV3FIaE9CMUJCTUhBeGsK/05wJD90CfuxAdXMJWIvLWCqxbFMqODJ
            ftWvzago12NoBsDYVdyYrDkdvxQ5j+OmSUe/TbOM8/07J96L4TCRRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rlx8p27kd9tr4sft5zym6h2fwyu54gkce4q7c2t5nrtxd64jvd3qntk7f6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYmFYcUxwSzdHcEVZVC9L
            ZVJhby9oVThjcGVCV1lmNlBDRDM2eG5IelRzCnpIVzBhUWFNUzlKWE1rbUV1am5z
            dHpTLzdBTGY5a1M3SllWQzRMbDZuUGsKLS0tIFEvK2tENU0rK1hobWU1YlZFaDZO
            Slp4cFpNUTR4STA4eGtkVHZqKy9pRWcKttknQ6GEkdHyHYCFpp28TKDEurhWTSm3
            aCud9usjmNnY/hZuWhdMDffbOg3wKowEgtN1y54PDfVdU9wEYqGb3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18v7nxk3e5p2xjtpe7uxv2jz9zz624tkscpkcr6fepc0k6vvvfdgq5mduj8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieVR3SnFJR2xNNVlkUUg3
            ZWtkZE91NjFVZVpoQlB0TWl0T1dCbTJaYUFzCjRvNGN1eWorWXovcXpyaUp1ZDVr
            ZkxsNnVEb25PMEVUUloyOFJRN2NsNkUKLS0tIGpjbld1ZGRGV2dMb25OY2wwRXNE
            dm1VWGhISkwyRWp5NnJEZGdEOW5laFEKLEEL5z40MVvNZzaAFC7yZxuzNenziF6w
            dOHPbeCw88+UJoBjQ80h41zJDals1Hq8T0/vq8btjExWcuCv1kFpbg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19exrq2t6lkchn08mhmxvywcsq2eur6h0jpz4zqrtvkvume37c3ysx8usjq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTG1rdWhCa3g1aWZyWHNT
            RHl4ZzVMV0VBcHI2d2ZNNW4vVm1IWEZBWmdRCjhYcVIrOW1yMFVpWXNWK2FGVnov
            YVdITWRiQkV5dzVRdjlHRUxjWkp5QTQKLS0tIFVRSS9VK1cxaVhXQ2lzQ3crSG9s
            ZVpKa0pUck85cVJabml6OWhYNndKb1kKhKsu+cX74POETm8IVDkVasCtpGy6ZrEz
            uRzEcJ1LVm4hmDBX0AI46IrMq5dUbSEK+vfcu5hugIAq9H+ZaQLG6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-24T13:49:57Z"
    mac: ENC[AES256_GCM,data:ZzBFAVZuZiFEUoFet4XEj/aSzTWhK/rJlzSFKhc0gW1hiZCX2h0zjFQmxdr308FCDMrJ46RjO4c9etFPPdM5gqJKVOmHClWpumYSfGuOJwNxj/zKeXPI04Sg8WPw+t0YAEWYfO0fjKUwWHE6p3OixyxmY0UM4rN1pApmvYdEybU=,iv:WMZWg9JGM5U8libiW0wIjLZ+TonaCefMYTp+LVQlPQs=,tag:3dnF5v7e4AxHuqHlbsX16w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
