name: "Checking EditorConfig"
permissions: read-all
on:
  # avoids approving first time contributors
  pull_request_target:
    branches-ignore:
      - 'release-**'

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "github.repository_owner == 'Lehmanator' && !contains(github.event.pull_request.title, '[skip treewide]')"
    steps:

    - name: Get list of changed files from PR
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_FOR_UPDATE }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api \
          repos/NixOS/nixpkgs/pulls/${{github.event.number}}/files --paginate \
          | jq '.[] | select(.status != "removed") | .filename' \
          > "$HOME/changed_files"

    - name: print list of changed files
      run: |
        cat "$HOME/changed_files"

    - uses: actions/checkout@4
      with:
        # pull_request_target checks out the base branch by default
        ref: refs/pull/${{ github.event.pull_request.number }}/merge

    # https://github.com/cachix/install-nix-action
    - uses: cachix/install-nix-action@30
      with:
        # nixpkgs commit is pinned so that it doesn't break
        # editorconfig-checker 2.4.0
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/c473cc8714710179df205b153f4e9fa007107ff9.tar.gz
        extra_nix_config: |
          extra-trusted-public-keys = lehmanator.cachix.org-1:kT+TO3tnSoz+lxk2YZSsMOtVRZ7Gc57jaKWL57ox1wU=
          extra-substituters = https://lehmanator.cachix.org/

    # TODO: Use new nix shell command
    - name: Checking EditorConfig
      run: |
        nix-shell -p editorconfig-checker --run 'xargs -r editorconfig-checker -disable-indent-size' < "$HOME/changed_files"

    - if: ${{ failure() }}
      run: |
        echo "::error :: Hey! It looks like your changes don't follow our editorconfig settings. Read https://editorconfig.org/#download to configure your editor so you never see this error again."
